import type { Standing } from "@/types/tournament.type";

export const MOCK_STANDINGS_PARTICIPANTS = [
  { _id: "demo-p1", fullName: "Chen Wei", username: "chenw" },
  { _id: "demo-p2", fullName: "Liu Mei", username: "liumei" },
  { _id: "demo-p3", fullName: "Park Jin", username: "parkj" },
  { _id: "demo-p4", fullName: "Raj Singh", username: "rajs" },
  { _id: "demo-p5", fullName: "Emma Larsen", username: "emmal" },
] as const;

export const MOCK_STANDINGS: Standing[] = [
  {
    participant: MOCK_STANDINGS_PARTICIPANTS[0],
    rank: 1,
    played: 4,
    won: 4,
    lost: 0,
    drawn: 0,
    setsWon: 12,
    setsLost: 3,
    setsDiff: 9,
    pointsScored: 198,
    pointsConceded: 142,
    pointsDiff: 56,
    points: 12,
    form: ["W", "W", "W", "W"],
  },
  {
    participant: MOCK_STANDINGS_PARTICIPANTS[1],
    rank: 2,
    played: 4,
    won: 3,
    lost: 1,
    drawn: 0,
    setsWon: 10,
    setsLost: 5,
    setsDiff: 5,
    pointsScored: 176,
    pointsConceded: 151,
    pointsDiff: 25,
    points: 9,
    form: ["W", "L", "W", "W"],
  },
  {
    participant: MOCK_STANDINGS_PARTICIPANTS[2],
    rank: 3,
    played: 4,
    won: 2,
    lost: 2,
    drawn: 0,
    setsWon: 8,
    setsLost: 8,
    setsDiff: 0,
    pointsScored: 165,
    pointsConceded: 168,
    pointsDiff: -3,
    points: 6,
    form: ["W", "W", "L", "L"],
  },
  {
    participant: MOCK_STANDINGS_PARTICIPANTS[3],
    rank: 4,
    played: 4,
    won: 1,
    lost: 3,
    drawn: 0,
    setsWon: 5,
    setsLost: 10,
    setsDiff: -5,
    pointsScored: 148,
    pointsConceded: 179,
    pointsDiff: -31,
    points: 3,
    form: ["L", "W", "L", "L"],
  },
  {
    participant: MOCK_STANDINGS_PARTICIPANTS[4],
    rank: 5,
    played: 4,
    won: 0,
    lost: 4,
    drawn: 0,
    setsWon: 2,
    setsLost: 12,
    setsDiff: -10,
    pointsScored: 121,
    pointsConceded: 198,
    pointsDiff: -77,
    points: 0,
    form: ["L", "L", "L", "L"],
  },
];

export const MOCK_SCORER = {
  player1: { name: "Chen Wei", initials: "CW" },
  player2: { name: "Park Jin", initials: "PJ" },
  side1Score: 9,
  side2Score: 7,
  side1Sets: 1,
  side2Sets: 0,
  currentGame: 2,
  games: [
    { gameNumber: 1, side1Score: 11, side2Score: 8, completed: true },
    { gameNumber: 2, side1Score: 9, side2Score: 7, completed: false },
  ],
} as const;
